Repository coreemu/core, pull requests merged in 2020-01, with the labels that each got.

#329 fix for custom services not setting service.configs when reading xml
  daemon/core/xml/corexml.py
Labels: bug

#330 added get_interfaces to grpc client
  daemon/core/api/grpc/client.py
Labels: enhancement

#339 Coretk smallfix
  daemon/core/gui/coreclient.py
  daemon/core/gui/dialogs/copyserviceconfig.py
Labels: cleanup

#340 Fix typo in installer
  install.sh
Labels: bug

#341 update dependency installer to python3
  install.sh
Labels: cleanup

#342 Enhancement/disable grpc client proxy
  daemon/core/api/grpc/client.py
  daemon/core/gui/app.py
  daemon/core/gui/coreclient.py
  daemon/scripts/coretk-gui
Labels: enhancement

#344 Enhancement/type hinting
  daemon/core/api/grpc/client.py
  daemon/core/api/grpc/events.py
  daemon/core/api/grpc/grpcutils.py
  daemon/core/api/grpc/server.py
  daemon/core/config.py
  daemon/core/emane/bypass.py
  daemon/core/emane/commeffect.py
  daemon/core/emane/emanemanager.py
  daemon/core/emane/emanemanifest.py
  daemon/core/emane/emanemodel.py
  daemon/core/emane/ieee80211abg.py
  daemon/core/emane/nodes.py
  daemon/core/emane/rfpipe.py
  daemon/core/emane/tdma.py
  daemon/core/emulator/coreemu.py
  daemon/core/emulator/distributed.py
  daemon/core/emulator/emudata.py
  daemon/core/emulator/session.py
  daemon/core/emulator/sessionconfig.py
  daemon/core/errors.py
  daemon/core/location/corelocation.py
  daemon/core/location/event.py
  daemon/core/location/mobility.py
  daemon/core/nodes/base.py
  daemon/core/nodes/client.py
  daemon/core/nodes/docker.py
  daemon/core/nodes/interface.py
  daemon/core/nodes/lxd.py
  daemon/core/nodes/netclient.py
  daemon/core/nodes/network.py
  daemon/core/nodes/physical.py
  daemon/core/plugins/sdt.py
  daemon/core/services/coreservices.py
  daemon/core/utils.py
  daemon/core/xml/corexml.py
  daemon/core/xml/corexmldeployment.py
  daemon/core/xml/emanexml.py
Labels: enhancement

#343 Coregui typehint
  daemon/core/gui/app.py
  daemon/core/gui/coreclient.py
  daemon/core/gui/dialogs/about.py
  daemon/core/gui/dialogs/alerts.py
  daemon/core/gui/dialogs/canvassizeandscale.py
  daemon/core/gui/dialogs/canvaswallpaper.py
  daemon/core/gui/dialogs/colorpicker.py
  daemon/core/gui/dialogs/copyserviceconfig.py
  daemon/core/gui/dialogs/customnodes.py
  daemon/core/gui/dialogs/dialog.py
  daemon/core/gui/dialogs/emaneconfig.py
  daemon/core/gui/dialogs/hooks.py
  daemon/core/gui/dialogs/linkconfig.py
  daemon/core/gui/dialogs/marker.py
  daemon/core/gui/dialogs/mobilityconfig.py
  daemon/core/gui/dialogs/mobilityplayer.py
  daemon/core/gui/dialogs/nodeconfig.py
  daemon/core/gui/dialogs/nodeservice.py
  daemon/core/gui/dialogs/observers.py
  daemon/core/gui/dialogs/preferences.py
  daemon/core/gui/dialogs/servers.py
  daemon/core/gui/dialogs/serviceconfig.py
  daemon/core/gui/dialogs/sessionoptions.py
  daemon/core/gui/dialogs/sessions.py
  daemon/core/gui/dialogs/shapemod.py
  daemon/core/gui/dialogs/throughput.py
  daemon/core/gui/dialogs/wlanconfig.py
  daemon/core/gui/errors.py
  daemon/core/gui/graph/edges.py
  daemon/core/gui/graph/graph.py
  daemon/core/gui/graph/node.py
  daemon/core/gui/graph/shape.py
  daemon/core/gui/graph/shapeutils.py
  daemon/core/gui/graph/tooltip.py
  daemon/core/gui/images.py
  daemon/core/gui/interface.py
  daemon/core/gui/menuaction.py
  daemon/core/gui/menubar.py
  daemon/core/gui/nodeutils.py
  daemon/core/gui/statusbar.py
  daemon/core/gui/task.py
  daemon/core/gui/themes.py
  daemon/core/gui/toolbar.py
  daemon/core/gui/tooltip.py
  daemon/core/gui/validation.py
  daemon/core/gui/widgets.py
  ns3/build/lib/corens3/__init__.py
  ns3/build/lib/corens3/obj.py
  ns3/setup.py
Labels: enhancement

#345 updates to log exceptions during threadpool, avoid errors when hwaddr…
  daemon/core/nodes/interface.py
  daemon/core/utils.py
Labels: bug

#346 update to place the terminal command in quotes
  daemon/core/gui/coreclient.py
Labels: bug

#348 updates to cases when checking existing bridges using ip -j returns a…
  daemon/core/nodes/netclient.py
Labels: bug

#349 updated utils.validate_mac format to use unix expanded to avoid singu…
  daemon/core/utils.py
  daemon/tests/test_utils.py
Labels: cleanup

#350 Bugfix/frr babel wireless
  daemon/core/services/frr.py
Labels: bug

#351 removed rtype and param typing from doc strings to help avoid maintai…
  daemon/core/api/grpc/client.py
  daemon/core/api/grpc/events.py
  daemon/core/api/grpc/grpcutils.py
  daemon/core/api/grpc/server.py
  daemon/core/config.py
  daemon/core/emane/commeffect.py
  daemon/core/emane/emanemanager.py
  daemon/core/emane/emanemanifest.py
  daemon/core/emane/emanemodel.py
  daemon/core/emulator/coreemu.py
  daemon/core/emulator/distributed.py
  daemon/core/emulator/emudata.py
  daemon/core/emulator/session.py
  daemon/core/emulator/sessionconfig.py
  daemon/core/gui/graph/graph.py
  daemon/core/gui/toolbar.py
  daemon/core/location/corelocation.py
  daemon/core/location/event.py
  daemon/core/location/mobility.py
  daemon/core/nodes/base.py
  daemon/core/nodes/client.py
  daemon/core/nodes/docker.py
  daemon/core/nodes/interface.py
  daemon/core/nodes/lxd.py
  daemon/core/nodes/netclient.py
  daemon/core/nodes/network.py
  daemon/core/nodes/physical.py
  daemon/core/plugins/sdt.py
  daemon/core/services/__init__.py
  daemon/core/services/coreservices.py
  daemon/core/utils.py
  daemon/core/xml/emanexml.py
Labels: cleanup

#347 Coretk fix
  daemon/core/gui/coreclient.py
  daemon/core/gui/data/icons/cancel.png
  daemon/core/gui/data/icons/delete.png
  daemon/core/gui/data/icons/shutdown.png
  daemon/core/gui/dialogs/sessions.py
  daemon/core/gui/images.py
  daemon/core/gui/themes.py
Labels: enhancement

#352 Coretk fix
  Pipfile
  daemon/core/gui/coreclient.py
  daemon/core/gui/dialogs/sessions.py
  daemon/core/gui/graph/graph.py
  daemon/core/gui/menuaction.py
  daemon/core/gui/menubar.py
Labels: coretk

#360 updates for coretk to default to assigning global ip6 addresses
  daemon/core/gui/coreclient.py
  daemon/core/gui/interface.py
Labels: enhancement
