Repository coreemu/core, pull requests merged in 2020-03, with the labels that each got.

#386 Coretk enhance/scaling
  daemon/core/gui/app.py
  daemon/core/gui/dialogs/preferences.py
  daemon/core/gui/themes.py
  daemon/core/gui/validation.py
Labels: enhancement

#383 Coretk enhance/disable runtime editing custom service config
  daemon/core/api/grpc/grpcutils.py
  daemon/core/gui/coreclient.py
  daemon/core/gui/dialogs/serviceconfig.py
  daemon/core/gui/graph/graph.py
  daemon/core/gui/graph/node.py
  daemon/core/gui/menubar.py
  daemon/core/gui/nodeutils.py
  daemon/core/gui/toolbar.py
Labels: enhancement

#409 Enhancement/enum cleanup
  daemon/core/api/grpc/events.py
  daemon/core/api/grpc/grpcutils.py
  daemon/core/api/grpc/server.py
  daemon/core/api/tlv/coreapi.py
  daemon/core/api/tlv/corehandlers.py
  daemon/core/api/tlv/dataconversion.py
  daemon/core/api/tlv/enumerations.py
  daemon/core/config.py
  daemon/core/emane/emanemanager.py
  daemon/core/emane/nodes.py
  daemon/core/emulator/enumerations.py
  daemon/core/emulator/session.py
  daemon/core/emulator/sessionconfig.py
  daemon/core/location/geo.py
  daemon/core/location/mobility.py
  daemon/core/nodes/base.py
  daemon/core/nodes/docker.py
  daemon/core/nodes/interface.py
  daemon/core/nodes/lxd.py
  daemon/core/nodes/network.py
  daemon/core/nodes/physical.py
  daemon/core/plugins/sdt.py
  daemon/core/services/coreservices.py
  daemon/core/services/quagga.py
  daemon/core/xml/corexml.py
  daemon/scripts/core-daemon
  daemon/scripts/coresendmsg
  daemon/tests/test_core.py
  daemon/tests/test_grpc.py
  daemon/tests/test_gui.py
  daemon/tests/test_links.py
  daemon/tests/test_xml.py
Labels: cleanup

#411 updates to basic range model configuration settings to allow 0 values…
  daemon/core/location/mobility.py
Labels: bug

#414 Enable OSPFv2 Adjacency Widget to work with FRR
  gui/widget.tcl
Labels: enhancement

#416 Enhancement/emane links
  .github/workflows/daemon-checks.yml
  daemon/core/emane/emanemanager.py
  daemon/core/emane/linkmonitor.py
  daemon/core/plugins/sdt.py
  daemon/core/xml/corexml.py
Labels: enhancement

#418 switched core emulator data files from using namedtuples to backporte…
  .github/workflows/daemon-checks.yml
  daemon/Pipfile.lock
  daemon/core/api/grpc/events.py
  daemon/core/api/tlv/corehandlers.py
  daemon/core/api/tlv/dataconversion.py
  daemon/core/emulator/data.py
  daemon/core/emulator/session.py
  daemon/core/nodes/base.py
  daemon/core/nodes/network.py
  daemon/core/services/coreservices.py
  daemon/requirements.txt
  daemon/setup.py.in
Labels: enhancement
