Repository coreemu/core, pull requests merged in 2020-07, with the labels that each got.

#484 Enhancement/runtime emane link
  daemon/core/api/grpc/grpcutils.py
  daemon/core/api/grpc/server.py
  daemon/core/emane/commeffect.py
  daemon/core/emane/emanemanager.py
  daemon/core/emane/emanemodel.py
  daemon/core/emane/nodes.py
  daemon/core/emulator/session.py
  daemon/core/nodes/base.py
  daemon/core/nodes/interface.py
  daemon/core/services/emaneservices.py
  daemon/core/xml/corexml.py
  daemon/core/xml/corexmldeployment.py
  daemon/core/xml/emanexml.py
  daemon/tests/conftest.py
Labels: enhancement

#490 Enhancement/poetry invoke
  .github/workflows/daemon-checks.yml
  .gitignore
  Makefile.am
  configure.ac
  daemon/.gitignore
  daemon/.pre-commit-config.yaml
  daemon/MANIFEST.in
  daemon/Makefile.am
  daemon/Pipfile
  daemon/Pipfile.lock
  daemon/core/nodes/docker.py
  daemon/poetry.lock
  daemon/pyproject.toml
  daemon/requirements.txt
  daemon/setup.cfg
  daemon/setup.py.in
  docs/install.md
  install.sh
  scripts/.gitignore
  scripts/Makefile.am
  scripts/core-daemon.in
  scripts/core-daemon.service.in
  tasks.py
Labels: enhancement

#493 Increase height of options dialogue in TCL gui
  gui/plugins.tcl
Labels: enhancement

#494 Update frr.py to add staticd to daemons list
  daemon/core/services/frr.py
Labels: enhancement

#499 Enhancement/pygui wrappers
  daemon/core/gui/coreclient.py
  daemon/core/gui/dialogs/alerts.py
  daemon/core/gui/dialogs/configserviceconfig.py
  daemon/core/gui/dialogs/emaneconfig.py
  daemon/core/gui/dialogs/hooks.py
  daemon/core/gui/dialogs/linkconfig.py
  daemon/core/gui/dialogs/mobilityconfig.py
  daemon/core/gui/dialogs/mobilityplayer.py
  daemon/core/gui/dialogs/nodeconfig.py
  daemon/core/gui/dialogs/serviceconfig.py
  daemon/core/gui/dialogs/sessionoptions.py
  daemon/core/gui/dialogs/sessions.py
  daemon/core/gui/dialogs/wlanconfig.py
  daemon/core/gui/frames/link.py
  daemon/core/gui/frames/node.py
  daemon/core/gui/graph/edges.py
  daemon/core/gui/graph/graph.py
  daemon/core/gui/graph/node.py
  daemon/core/gui/images.py
  daemon/core/gui/interface.py
  daemon/core/gui/nodeutils.py
  daemon/core/gui/statusbar.py
  daemon/core/gui/toolbar.py
  daemon/core/gui/widgets.py
  daemon/core/gui/wrappers.py
Labels: cleanup

#502 Cleanup/pygui session wrapper
  daemon/core/api/grpc/grpcutils.py
  daemon/core/api/grpc/server.py
  daemon/core/emulator/session.py
  daemon/core/gui/coreclient.py
  daemon/core/gui/dialogs/canvassizeandscale.py
  daemon/core/gui/dialogs/configserviceconfig.py
  daemon/core/gui/dialogs/copyserviceconfig.py
  daemon/core/gui/dialogs/emaneconfig.py
  daemon/core/gui/dialogs/find.py
  daemon/core/gui/dialogs/hooks.py
  daemon/core/gui/dialogs/linkconfig.py
  daemon/core/gui/dialogs/mobilityconfig.py
  daemon/core/gui/dialogs/mobilityplayer.py
  daemon/core/gui/dialogs/nodeconfigservice.py
  daemon/core/gui/dialogs/nodeservice.py
  daemon/core/gui/dialogs/runtool.py
  daemon/core/gui/dialogs/serviceconfig.py
  daemon/core/gui/dialogs/sessionoptions.py
  daemon/core/gui/dialogs/sessions.py
  daemon/core/gui/dialogs/wlanconfig.py
  daemon/core/gui/frames/link.py
  daemon/core/gui/graph/graph.py
  daemon/core/gui/graph/node.py
  daemon/core/gui/task.py
  daemon/core/gui/wrappers.py
  daemon/proto/core/api/grpc/core.proto
  daemon/proto/core/api/grpc/emane.proto
  daemon/proto/core/api/grpc/services.proto
Labels: cleanup

#504 Bugfix/emane mobility
  daemon/core/api/grpc/grpcutils.py
  daemon/core/api/grpc/server.py
  daemon/core/emane/emanemodel.py
  daemon/core/gui/coreclient.py
  daemon/core/gui/graph/node.py
  daemon/core/gui/nodeutils.py
  daemon/core/location/mobility.py
Labels: bug
