Repository coreemu/core, pull requests merged in 2020-11, with the labels that each got.

#514 add support for /tmp/pycore.nnnnn/environment file, DRY up env merges
  daemon/core/emulator/session.py
  daemon/core/utils.py
Labels: enhancement

#525 Feature/pygui multiple links
  daemon/core/gui/coreclient.py
  daemon/core/gui/dialogs/linkconfig.py
  daemon/core/gui/graph/edges.py
  daemon/core/gui/graph/graph.py
  daemon/core/gui/graph/node.py
  daemon/core/gui/interface.py
  daemon/core/gui/nodeutils.py
Labels: feature

#527 Typo in services.md
  docs/services.md
Labels: cleanup

#529 updates for link configuration to calculate a limit when bandwidth/delay are present
  daemon/core/api/tlv/corehandlers.py
  daemon/core/configservices/frrservices/services.py
  daemon/core/configservices/quaggaservices/services.py
  daemon/core/nodes/base.py
  daemon/core/nodes/interface.py
  daemon/core/nodes/network.py
  daemon/core/nodes/physical.py
  daemon/core/services/frr.py
  daemon/core/services/quagga.py
Labels: enhancement
